# -*- coding: utf-8 -*-
"""Actividad1 - POO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zm_LyB4SV9BHeNaxrJ7w-Qi9kZ3cWX_6
"""

#Ejercicio 4

class familia:
    def __init__(self,nombre,edad):
        self.nombre=nombre
        self.edad=edad
    def __str__(self):
        return f'{self.nombre} tiene {self.edad}'
class persona:
    def __init__(self,edad_1):
        self.juan=familia("juan",edad_1)
        self.alberto=familia("alberto",edad_1*2/3)
        self.ana=familia("ana",edad_1*4/3)
        self.mama=familia("mama",self.juan.edad+self.alberto.edad+self.ana.edad)
edad_1=int(input("dijite la edad de juan: "))
hola=persona(edad_1)
print(hola.juan)
print(hola.alberto)
print(hola.ana)
print(hola.mama)

#Ejercicio 12

class caracteristicas:
    def __init__(self, nombre):
        self.nombre=nombre
        self.pago_bruto=48*5000
        self.retencion=self.pago_bruto*0.125
        self.pago_neto=self.pago_bruto-self.retencion
    def __str__(self):
        return f'{self.nombre}-salario brutro-{self.pago_bruto}-retencion de fuente-{self.retencion}-salario neto-{self.pago_neto}'
class trabajador:
    def __init__(self,nombre):
        self.nombreca=caracteristicas(nombre)
trabajadores=[]
personaje=input("digite su nombre: ")
trabajadores.append(trabajador(personaje))
print(trabajadores[0].nombreca)

#Ejercicio 14

class numero:
    def __init__(self, n):
        self.numeron=n
    def cuadrado(self):
        return self.numeron**2
    def cubo(self):
        return self.numeron**3
numerou=int(input("digite el numero: "))
resultado=numero(numerou)
print(f'el numero es {resultado.numeron} cuadrado es {resultado.cuadrado()} cubo es {resultado.cubo()}')

#Ejercicio 17

import math
class numero:
    def __init__(self, n):
        self.numeron=n
    def area(self):
        return self.numeron**2*math.pi
    def circunferencia(self):
        return self.numeron*2*math.pi
numerou=int(input("digite el numero: "))
resultado=numero(numerou)
print(f'el numero es {resultado.numeron} el area {resultado.area()} lo longitud de circunferencia  {resultado.circunferencia()}')