# -*- coding: utf-8 -*-
"""Actividad1_3 - POO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-CunNCWL8x6C2KmSZG66w6_DGYl3fNc
"""

class numero:
    def __init__(self, n):
        self.numeron=n
    def cuadrado(self):
        return self.numeron**2
    def cubo(self):
        return self.numeron**3
numerou=int(input("digite el numero: "))
resultado=numero(numerou)
print(f'el numero es {resultado.numeron} cuadrado es {resultado.cuadrado()} cubo es {resultado.cubo()}')