# -*- coding: utf-8 -*-
"""Actividad1_4 - POO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JHTVHv28NLgujGnmImtmkCOOcKyuJMJC
"""

import math
class numero:
    def __init__(self, n):
        self.numeron=n
    def area(self):
        return self.numeron**2*math.pi
    def circunferencia(self):
        return self.numeron*2*math.pi
numerou=int(input("digite el numero: "))
resultado=numero(numerou)
print(f'el numero es {resultado.numeron} el area {resultado.area()} lo longitud de circunferencia  {resultado.circunferencia()}')